### ISSUE TITLE
Need some tests

### ISSUE THREAD

**Issue by peter279k** [ApertureLab/Gandi-API#4]
To let this third-party API behaviors be verified and reliable, it should add some tests to resolve this issue.

@Narno, what do you think about this?

Once this issue is accepted by repository owner, I can work on this :smile:.

**Comment by Narno** [comment]
Hello @peter279k , sorry for the elays (I missed the mention...).

This lib is very old, and needs very numerous of enhancements: the used API is deprecated, PHP version is so old, etc.

**Comment by peter279k** [comment]
Ok. I look at another Gandi API. And thanks for your reply.
